/**
 * 비즈니스 에러 코드 (명세 8. 에러 처리 규칙)
 */
export const ErrorCode = {
  INVALID_QUEUE_STATE: 'INVALID_QUEUE_STATE',
  QUEUE_ALREADY_JOINED: 'QUEUE_ALREADY_JOINED',
  NOT_ACTIVE_QUEUE: 'NOT_ACTIVE_QUEUE',
  QUEUE_EXPIRED: 'QUEUE_EXPIRED',
  CONTRACT_ALREADY_EXISTS: 'CONTRACT_ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RESALE_NOT_APPROVED: 'RESALE_NOT_APPROVED',
  NOT_FOUND: 'NOT_FOUND',
  UNIT_NOT_AVAILABLE: 'UNIT_NOT_AVAILABLE',
  RESALE_NOT_LISTED: 'RESALE_NOT_LISTED',
  // Notifications (STEP 5)
  INVALID_DEVICE_TOKEN: 'INVALID_DEVICE_TOKEN',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_READ: 'NOTIFICATION_ALREADY_READ',
  PUSH_PROVIDER_ERROR: 'PUSH_PROVIDER_ERROR',
  SMS_PROVIDER_ERROR: 'SMS_PROVIDER_ERROR',
  EMAIL_PROVIDER_ERROR: 'EMAIL_PROVIDER_ERROR',
  NOTIFICATION_DISPATCH_FAILED: 'NOTIFICATION_DISPATCH_FAILED',
  RETRY_LIMIT_EXCEEDED: 'RETRY_LIMIT_EXCEEDED',
  // Facility / Seat / Reservation
  SEAT_NOT_AVAILABLE: 'SEAT_NOT_AVAILABLE',
  SEAT_BLOCKED: 'SEAT_BLOCKED',
  SEAT_NOT_GREEN: 'SEAT_NOT_GREEN',
  SEAT_NOT_YELLOW: 'SEAT_NOT_YELLOW',
  WAITING_LIMIT_REACHED: 'WAITING_LIMIT_REACHED',
  DUPLICATE_WAITING: 'DUPLICATE_WAITING',
  CONFIRMED_ALREADY_EXISTS: 'CONFIRMED_ALREADY_EXISTS',
  // Seat Resale
  RESERVATION_NOT_CONFIRMED: 'RESERVATION_NOT_CONFIRMED',
  RESALE_NOT_OWNER: 'RESALE_NOT_OWNER',
  RESALE_ALREADY_LISTED: 'RESALE_ALREADY_LISTED',
  RESALE_FIXED_PRICE_REQUIRED: 'RESALE_FIXED_PRICE_REQUIRED',
  RESALE_NEGOTIABLE_RANGE: 'RESALE_NEGOTIABLE_RANGE',
  RESALE_MARKET_PRICE_FAILED: 'RESALE_MARKET_PRICE_FAILED',
  RESALE_OFFER_OUT_OF_RANGE: 'RESALE_OFFER_OUT_OF_RANGE',
  RESALE_PRICE_OUT_OF_RANGE: 'RESALE_PRICE_OUT_OF_RANGE',
  RESALE_TOO_EARLY: 'RESALE_TOO_EARLY',
  AGENT_CODE_INVALID: 'AGENT_CODE_INVALID',
  AGENT_COMPANY_MISMATCH: 'AGENT_COMPANY_MISMATCH',
  AGENT_CODE_TAKEN: 'AGENT_CODE_TAKEN',
  USER_ALREADY_AGENT: 'USER_ALREADY_AGENT',
  COMMISSION_RATE_INVALID: 'COMMISSION_RATE_INVALID',
  DUPLICATE_LOGIN_ID: 'DUPLICATE_LOGIN_ID',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export class BusinessError extends Error {
  constructor(
    public readonly code: ErrorCodeType,
    message: string,
    public readonly statusCode: number = 400,
  ) {
    super(message);
    this.name = 'BusinessError';
    Object.setPrototypeOf(this, BusinessError.prototype);
  }
}
